site_name: is-a.dev Docs

theme:
  name: compose
  favicon: img/favicon.ico
  logo: img/banner.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Domain Structure: domain_structure/index.md
  - GitHub Pages: github_pages/index.md
  - Hashnode Blog: hashnode/index.md
  - Railway: railway/index.md
  - Other Services: other/index.md
